### ISSUE TITLE
[Comment] Regarding the NUMA locality of your code on TR

### ISSUE THREAD

**Issue by Gartral** [PlummersSoftwareLLC/Primes#123]
As I alluded too in the video a bit ago, I believe the speed "boost hump" you saw was because of NUMA locality in Linux. 
See this doc for more info and tell me if you're thinking the same: https://www.kernel.org/doc/html/latest/admin-guide/mm/numaperf.html

And don't forget to check out Valgrind, it's meant to help you find and fix memory leaks in code, but it's very useful in profiling threads as well! http://cs.ecs.baylor.edu/~donahoo/tools/valgrind/

As always, I enjoyed your video! Thanks for making them! You're a pleasure to watch and talk too! 

(You can go ahead and close this ticket, it's not a bug.)

**Comment by rbergen** [comment]
Closing this, as the author indicated it can be.
