### ISSUE TITLE
[Comment] Intel(R) Xeon(R) CPU E5-2630 v4

### ISSUE THREAD

**Issue by smilima** [PlummersSoftwareLLC/Primes#128]
I have access to a Intel(R) Xeon(R) CPU E5-2630 v4 processor which has 10 cores and 20 threads I would be willing to use to run anyone's C or C++ code.  It is a little old as far as processors go, but it may be faster than what we have access to.  Reply to this if you are interested.

**Comment by marghidanu** [comment]
If you're willing we could set it up as a GitHub runner.

**Comment by smilima** [comment]
Sure, however the machine can’t connect to the internet due to it being a government machine. I can pull the repo and run code whenever anyone would like me to.

**Comment by marghidanu** [comment]
> Sure, however the machine can’t connect to the internet due to it being a government machine.

:)) alright, then maybe you can put together a Makefile to run the tests for you locally.
