### ISSUE TITLE
Dockerfile each implementation

### ISSUE THREAD

**Issue by bundgaard** [PlummersSoftwareLLC/Primes#144]
Hello, 

Been sifting through some of the issues where we have discussions, and I'm not sure if it has been suggested before, but I would suggest we update all our implementations to be run from a Dockerfile, that way we have less to learn in terms of how each pipeline looks like and also we will be able to run each others implementations in an automated fashion.

Will update my own implementation to have a Dockerfile and then make a new pull-request.

Anyone who has other feedback to this suggestion?

**Comment by bundgaard** [comment]
I would like to this interesting tidbit, running the PrimeSieveGo in Docker actually reduces the throughput of the calculations, which I find odd.

Trying to dig deeper to find a root-cause but none so far.

It is still the same machine its running as described in the README

**Comment by marghidanu** [comment]
We already suggested to attach a Dockerfile for each implementation. Please check the CONTRIBUTING.md file. This is how we provision the run environment in the CI.
