### ISSUE TITLE
Merge `drag-race` and `master`

### ISSUE THREAD

**Issue by rhbvkleef** [PlummersSoftwareLLC/Primes#148]
It causes several problems to not have the majority of contributions be merged into `master`. As such, the proposal is to find a way to merge these two branches.

Dave requested this:

> My goal is to be able to keep the original branch with only a very few changes. I have a few checking queued up of my own, which I will check in, and then leave the main branch alone. I want as few changes in the main branch as possible to keep the tests similar from one episode to the next, but we can party alongside it for sure!

I think achieving the main goal Dave set out, and merging `drag-race` into master is not impossible.

@mike-barber proposed this: 

> Would it make sense to put Dave's original solutions in an "original" folder maybe?
> 
> Could be all in a single original folder, or each language could have an original folder with Dave's code in it, with community ones then labelled solution_x as usual.
> 
> One thing that could make this merge easier is doing it in two phases -
>
> 1. Merge main into drag-race
> 2. Then fix the paths in drag-race
> 
> Then maybe one day get rid of drag race entirely and just have main :)

I think this is mostly a good idea. The only problematic part is that Dave has implemented multiple solutions for C++, and so there would be multiple `original` folders. As such, numbering `original` would make sense.

Before we do this, however, I would like to get a comment from @davepl because we are getting close to encroaching on his contributions.

**Comment by marghidanu** [comment]
Keeping the main branch as it is is fine. We just need to tell GitHub that the “main” branch is actually called “drag-race”. :)

**Comment by rbergen** [comment]
I was wondering if there has been any (out-of-band) feedback from @davepl on @marghidanu's suggestion? It would save a lot of confusion with new submissions initially "defaulting" to the (current) "main" branch. Actually, I believe it will also make it easier to have branches in forks track the active base branch (being drag-race).

**Comment by rhbvkleef** [comment]
> I was wondering if there has been any (out-of-band) feedback from @davepl on @marghidanu's suggestion?

As far as I know, there isn't.

**Comment by rbergen** [comment]
@rhbvkleef Are you ok with closing this? I think we can, due to drag-race now being the default branch, and changes in the former main branch having been merged in drag-race via PR #193.

**Comment by rbergen** [comment]
I'm closing this for lack of objections :)
