### ISSUE TITLE
Incorrect results with square numbers.

### ISSUE THREAD

**Issue by realXCV** [PlummersSoftwareLLC/Primes#19]
If the sieveSize is the square of a prime number like 25 or 49, that last number won't be flagged as "not a prime" since the runSieve function will stop before evaluating the factors of its square root.

Might also apply if the size is 50.

#17 includes a fix for this issue for the CPP version.

**Comment by davepl** [comment]
Thanks, I’ve already fixed that one but good catch, I didn’t notice it until afterwards!  Last minute optimization… :-)

**Comment by davepl** [comment]
Fixed with my checkin, so closing!  Thanks!
