### ISSUE TITLE
parallel version question

### ISSUE THREAD

**Issue by ityonemo** [PlummersSoftwareLLC/Primes#210]
what exactly do we mean by a parallel version?  Is that 

1.  run the sieve on as many threads as possible and add up the results of each thread to get the # of executions?  (Gustafson scaling)

or

2. run one sieve across many threads and add up how many executions you get, total? (Amdahl scaling)

**Comment by rbergen** [comment]
In the lexicon of this project, "parallel" is simply defined as "uses more than one thread to execute the sieve runs". That allows for both types of multi-threaded approaches you mention, and leaves the choice which one is used to the developer of an implementation. 
For reference, @Kinematics has created a wide range of different implementations in C#, in one solution ([PrimeCSharp/solution_1](https://github.com/PlummersSoftwareLLC/Primes/tree/drag-race/PrimeCSharp/solution_1)). Some of those use an algorithm that uses multiple threads to run one sieve ("Amdahl scaling"), and in principle all of them can be run in parallel ("Gustafson scaling").

**Comment by ityonemo** [comment]
thanks for clarifying!  I'll implement both!  I'd propose being very careful about comparing implementations across the two different techniques, because the "Amdahl" scaling is going to generally be less performant than "Gustafson", and each is representative of a different type of task need paradigm ("in the real world" sometimes you will absolutely need Amdahl, and sometimes you are better off Gustafson).

**Comment by rbergen** [comment]
There's a whole different issue (#177) that discusses reporting on different approaches and algorithms. There is currently a PR (#195) open to make a start with adding implementation characteristics to implementation output, so we can start segmenting the reporting based on those. From the discussion on that PR one can already conclude that it will not be the final step in that area. :)

**Comment by ityonemo** [comment]
awesome!
