### ISSUE TITLE
`sed: illegal option -- r` when running on macOS.

### ISSUE THREAD

**Issue by JMuff22** [PlummersSoftwareLLC/Primes#296]
Running `make` on a macOS MBP 13" 2020 gives error `sed: illegal option -- r`. 

Catalina 10.15.7, Intel Core i7 (Quad). 

It runs the benchmarks but flags this error for each one. Unsure if it affects result.

**Comment by marghidanu** [comment]
Interesting, the tools package was developed under macOS, can you post the full output? Also please check if `sed` is located in `/usr/bin/sed`.

Since you are running Catalina please install `gnu-sed` from brew using the following command:
`brew install gnu-sed --with-default-names`

**Comment by JMuff22** [comment]
Semi resolved: 

`brew install gnu-sed` + replacing any instance of `sed` with `gsed` in the makefile fixes it. 

> Since you are running Catalina please install `gnu-sed` from brew using the following command:
> `brew install gnu-sed --with-default-names`

`Error: invalid option: --with-default-names`  unfortunately. 

Leaving open in case there is a workaround without changing the makefile.

**Comment by marghidanu** [comment]
You can try an alias on sed to gsed, in the meanwhile I will look for a replacement for this.

**Comment by marghidanu** [comment]
Since we're using Bash I think I can attempt to do the replacement directly in the variable. Will run a couple of tests locally to see if everything works as expected.

**Comment by marghidanu** [comment]
@JMuff22 since we're not running Catalina, can you try accessing my branch and use that for a small test?

**Comment by JMuff22** [comment]
@marghidanu Yes that works, running fine without sed alias. Thanks!

**Comment by marghidanu** [comment]
Awesome, will merge this later after we confirm that is also working under WSL

**Comment by marghidanu** [comment]
@JMuff22 All good, the fix is in place.
