### ISSUE TITLE
Question about rules

### ISSUE THREAD

**Issue by hamarb123** [PlummersSoftwareLLC/Primes#317]
Hi, I've devised an algorithm that is quite fast for the language it is and the base algorithm.
I believe that it is the base algorithm and it follows the rules, but I'm not certain.
It uses 8-bits for each stored value, but instead of storing every value, it only stores for the odd numbers starting at 3. It doesn't have any predefined primes (except 2 like the standard c++ one), so it's not a wheel algorithm.
Is this allowed? Is it 8-bits or 4-bits or other?
I don't see why it wouldn't be, but I wanted to check before I got it ready for PR.

**Comment by rbergen** [comment]
@hamarb123 I'm converting this question to a Discussion.
