### ISSUE TITLE
Improvements to the Swift implementation

### ISSUE THREAD

**Issue by odmir** [PlummersSoftwareLLC/Primes#385]
Hello! I am looking at the current Swift implementation of the sieve and have some changes in mind that in my machine lead to ~10x speed improvement. The thing is that I consider these changes to be relatively small, and since they don't change the algorithm in any way, I consider them unworthy of a separate solution.

The changes I'm considering are:

1. Changing the Dockerfile to use a more recent version of the language & Ubuntu 20.04 container instead of the current Ubuntu 18.04
2. Change the `Bit count` flag in the README to 8 bits since the implementation is using an array of booleans that each occupy 8 bits in memory, even if only one of those bits is used to represent the value (currently it's set to `unknown`)
3. Changes to `PrimeSwift/solution_1/Sources/PrimeSieveSwift/main.swift`:
	1. Delete the `BitArray` protocol definition (lines 3-7) that is unnecessarily being used as an existential and replace its use in line 33 by the concrete `struct BoolBitArray` that is already implemented
	2. Change `PrimeSieveSwift` from a class to a struct (at line 31) and make the `runSieve` method `mutating` (line 52) to indicate that the method mutates the struct
	3. Add the `bits=8` tag to the program output at line 117
	4. Change the benchmark duration from 10 seconds to 5 at line 125, so the benchmark doesn't take any longer than needed

Then there are more "stylistic" changes that make the code more idiomatic:
1. Replace the use of an implicitly unwrapped optional (IUO) at line 123 by initialising the `sieve` variable to an empty sieve instead (`var sieve: PrimeSieveSwift!` -> `var sieve = PrimeSieveSwift(limit: 0)`)
2. Replace the use of `idx % 2 != 0` by the more descriptive and idiomatic `!idx.isMultiple(of: 2)`
3. Rename the `PrimeSieveSwift` type to `PrimeSieve`
4. Rename the `bits` property to the more descriptive name, `isPrime`
5. Change lines 15-28 in the `BoolBitArray` to be a pair of subscript getter and setter, keeping the indexing implementation the same, and changing every use of the `bits` property to use the subscript operator like `bits[num]` and `bits[num] = false` (at lines 45, 58, 64 and 103), instead of the current `getBit` and `clearBit`

My first question is if I should contribute this as a separate new solution or to the existing one.

The contribution guidelines say this under [faithfulness](https://github.com/PlummersSoftwareLLC/Primes/blob/4ad4c6cf6a503ee4603d362f1e8f2f646e13a5c8/CONTRIBUTING.md#faithfulness): 

> It uses a class to encapsulate the sieve, or an equivalent feature in your language.

So my next question is if my change from a class to a struct falls under "equivalent feature". A C++ class is closer to a Swift struct than a Swift class, so I guess there is no issue here.

Thank you for your attention.

**Comment by tjol** [comment]
As I understand it (just as someone watching this)

 * A pull request with changes that improve the performance will be welcomed
 * Optimisations to existing solutions are preferred to new solutions
 * Cosmetic changes that do not improve performance are not appropriate
 * If there is a suitable construct called 'class' then this must be used. (This came up in relation to C# recently, which I think is similar to Swift in this regard)
