### ISSUE TITLE
error from make

### ISSUE THREAD

**Issue by Richhoef** [PlummersSoftwareLLC/Primes#439]
Whenever I execute the make command, I get the following error:
![image](https://user-images.githubusercontent.com/51912545/125953052-18b98c0f-f3bc-4a5b-ad91-6461561fc5e1.png)

This is since the merge commit from pull request #348 (SHA-1: e866254100a48714af053df764c7ae3da6af50b1).
The commit before (SHA-1:  2c7bbf93d8c157db547d9dac2937d38c188399c0) does work perfectly.

What am I doing wrong?

**Comment by rbergen** [comment]
It looks like CC (the C compiler) isn't installed, which is needed to build the node-uname module. What distribution are you running?

**Comment by Richhoef** [comment]
I am running Ubuntu 20.04

**Comment by rbergen** [comment]
Try running `sudo apt-get install build-essential` and then running make again.

**Comment by Richhoef** [comment]
That wasn't in the instructions ;)
But that helps! Thanks!

**Comment by rbergen** [comment]
> That wasn't in the instructions ;)

That's a good point. I've opened #444 to fix that.

**Comment by rbergen** [comment]
Closing after merge of #444.
