### ISSUE TITLE
Limit error

### ISSUE THREAD

**Issue by Garcar001** [PlummersSoftwareLLC/Primes#440]
When I run the PrimeSieveCSharp  version using the limit of 10 (instead of 1 million) I get a validation of false. It looks like countPrimes returns 5 instead of 4 for the bit array. Is anyone else seeing this?

**Comment by rbergen** [comment]
Exactly what file are you looking at? I'm getting the feeling it concerns the original C# implementation in the `original` branch. If so, no matter what is wrong with it, we're not going to touch it.

**Comment by Garcar001** [comment]
Yes, it was in the original C# implementation. Thanks.
