### ISSUE TITLE
'crystal build' fails with a segmentation fault

### ISSUE THREAD

**Issue by rbergen** [PlummersSoftwareLLC/Primes#456]
Since about a day, the Crystal/solution_1 `docker build` is failing with a segmentation fault both in the GitHub CI workflow, and locally.

When performed locally, the `docker build` yields the following output:
```
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 399B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/alpine:3.13                                                     5.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 1.96kB                                                                                0.0s
 => CACHED [build 1/5] FROM docker.io/library/alpine:3.13@sha256:f51ff2d96627690d62fee79e6eecd9fa87429a38142b5df8  0.0s
 => => resolve docker.io/library/alpine:3.13@sha256:f51ff2d96627690d62fee79e6eecd9fa87429a38142b5df8a3bfbb26061df  0.0s
 => [build 2/5] RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories     && apk add --no-cache bu  14.9s
 => [build 3/5] WORKDIR /opt/app                                                                                   0.2s
 => [build 4/5] COPY primes.cr .                                                                                   0.1s
 => ERROR [build 5/5] RUN crystal build primes.cr --release --static --no-debug                                    0.5s
------
 > [build 5/5] RUN crystal build primes.cr --release --static --no-debug:
#9 0.413 Invalid memory access (signal 11) at address 0x555ad47af84a
#9 0.453 [0x555a946a4186] ???
#9 0.453 [0x555a946a4153] ???
#9 0.453 [0x7f6e43397c8a] ???
```

I've created [a post on the Crystal forum](https://forum.crystal-lang.org/t/segmentation-fault-when-running-crystal-build/3530) to ask for assistance in solving this.

**Comment by rbergen** [comment]
Many thanks to @marghidanu for addressing the failure with #457. Keeping this issue open for updates concerning a fix in the Crystal compiler that will allows us to re-enable support for arm64.

**Comment by marghidanu** [comment]
I will definitely keep an eye on this since it's one of my favorite languages. Too bad they broke the compiler in this revision, let's see how fast they recover :)

**Comment by marghidanu** [comment]
This is the link for the official bug submission: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12854
I will keep an eye on this, unfortunately, it will probably take about two weeks until somebody will actually look at the build.

**Comment by marghidanu** [comment]
The issue with Alpine Linux seems to be stalling. @rbergen if you don't mind I will close this one down. Will come back to it later, hopefully, when they add official support for arm64 builds.

**Comment by rbergen** [comment]
@marghidanu Yeah, I'm seeing the same. Unfortunate to lose Crystal on arm64, but it is what it is for now.
