### ISSUE TITLE
Cleaning up minor C++ bugs, warnings and bad teaching style

### ISSUE THREAD

**Issue by Michaelangel007** [PlummersSoftwareLLC/Primes#53]
There are a few minor C++ warnings that set a bad precedent for people watching the videos who are new to the language.

1. `myDict ` has a key of type `const long` -- [it should be](https://github.com/davepl/Primes/blob/main/PrimeCPP/PrimeCPP.cpp#L23) `const long long`.  The last entry is 10,000,000,000L which overflows a signed 32-bit (2,147,483,647) and wraps around to 1,410,065,408 as the small snippet below demonstrates:

```
    for (auto i = table.begin(); i != table.end(); i++)
        printf( "%ld\n", i->first );
```
 The literal integer keys in the table should be using annotated with `LL`:
```
                {          10LL, 4         },                // Historical data for validating our results - the number of primes
                {         100LL, 25        },               // to be found under some limit, such as 168 primes under 1000
                {        1000LL, 168       },
                {       10000LL, 1229      },
                {      100000LL, 9592      },
                {     1000000LL, 78498     },
                {    10000000LL, 664579    },
                {   100000000LL, 5761455   },
                {  1000000000LL, 50847534  },
                { 10000000000LL, 455052511 }
```
2. There is a missing `int` cast in the sqrt() result in [Line #53](https://github.com/davepl/Primes/blob/main/PrimeCPP/PrimeCPP.cpp#L59). It should be:
```
    int q = (int) sqrt(sieveSize);
```

3. There is a missing literal double type annotation in [Line 129](https://github.com/davepl/Primes/blob/main/PrimeCPP/PrimeCPP.cpp#L129) for the microseconds case. The integer `1000000` should be annotated as a literal double type with either a `.` or `.0` suffix:
```
            sieve.printResults(false, duration_cast<microseconds>(steady_clock::now() - tStart).count() / 1000000., passes);
```

Other misc. comments.

* `validateResults()` is doing an extra `find()`. It should be only doing this [once](https://github.com/davepl/Primes/blob/main/PrimeCPP/PrimeCPP.cpp#L42):
```
      bool validateResults()
      {
          auto result = myDict.find(sieveSize);
          if (myDict.end() == result)
              return false;
          return result->second == countPrimes();
      }
```
* The table `myDict` is only used by `validateResults` yet it pollutes the class.  It be scoped within that function.  Unfortunately, I'm seeing a huge performance hit on my Threadripper 3960X when it is in the function.  Namely 8600 passes (class scope) vs 8000 passes  (function scope).  Looks like MSVC 2019 isn't properly inline the `static const map` initializer list when it is in the function scope? Might want to make a mention of the scoping performance issue.
* There are numerous edge-case bugs that assume `sieveSize` > 2 in `countPrimes()` and `printResults()`. They should be:
```
      void printResults(bool showResults, double duration, int passes)
      {
          if ((showResults && (sieveSize >= 2))
              printf("2, ");

      int countPrimes()
      {
          int count = (sieveSize >= 2);
```
* There is no comment on the _magic number_ of 1 for `count` in `printResults()` on [Line #83](https://github.com/davepl/Primes/blob/main/PrimeCPP/PrimeCPP.cpp#L83):
```
          int count = 1;
```
It should be written as:
```
          int count =  (sieveSize >= 2); // include first prime 2
```

Lastly, you might want to mention in a follow up video that is worth compiling at Warning Level 4 on MSVC `/W4` to catch type errors.  While the program will usually run if these are ignored these they are potentially problems lurking in the code.  While it can be tedious to "shut the compiler up" over trivial warnings professional programmers try to compile code with zero warnings at the highest level possible.

**Comment by davepl** [comment]
I'm the guy that ported the entire Win95 shell to NT at /W4 /WX (Edit: I should say I'm the poor guy that fixed all the warnings, I didn't port the whole thing by myself, to be clear!).  I'm a big fan of warnings and style, but I didn't write this code to pro standards as I didn't even know other people would see it, but how that they will, I'll clean it up!

**Comment by Michaelangel007** [comment]
Thanks for the cleanup!
