### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Liorst4** [PlummersSoftwareLLC/Primes#54]
Add a license to the code to prevent copyright related issues with viewer submitted code.

**Comment by rhbvkleef** [comment]
I agree. Adding a license was part of my proposal for maintaining this repository (https://github.com/davepl/Primes/issues/42#issuecomment-813008487). I proposed BSD-3, but I think this issue will be a fine place to propose other licenses, if people disagree with that proposal.

**Comment by rhbvkleef** [comment]
I would still like to hear from @davepl regarding this issue. I think he'll agree, but I think it is good to make sure of that. Do you think [BSD-3](https://opensource.org/licenses/BSD-3-Clause) is appropriate?

**Comment by rbergen** [comment]
@rhbvkleef & @marghidanu I believe we can close this. The choice for BSD-3 seems to work well.
