### ISSUE TITLE
Json output format reports wrong L1 cache sizes

### ISSUE THREAD

**Issue by fvbakel** [PlummersSoftwareLLC/Primes#558]
Json output format reports a wrong L1 datacache size.

Steps on Linux: 

1. `make DIRECTORY=PrimeC FORMATTER=json OUTPUT_FILE=result.json` reports:

```json
...
    "cache": {
        "l1d": 65536,
        "l1i": 65536,
        "l2": 524288,
        "l3": 4
    }
...
```
2. `getconf LEVEL1_DCACHE_SIZE` outputs: `32768`
3. `getconf LEVEL1_ICACHE_SIZE` outputs: `32768`

It seems that the json report uses the total L1 cache size for the instruction and data size. See generated output in [result.json.txt](https://github.com/PlummersSoftwareLLC/Primes/files/6912322/result.json.txt)

**Comment by rbergen** [comment]
The benchmark tool uses the [systeminformation npm package](https://www.npmjs.com/package/systeminformation) to collect system information, and reports it unchanged. That systeminformation package has its repo here: https://github.com/sebhildebrandt/systeminformation; you may want to open an issue there to report this. If a fix becomes available, we can look into bumping the dependency version up to it. Unless and until it is fixed upstream, there's nothing we can do about this.

**Comment by marghidanu** [comment]
@fvbakel I followed your discussion on the issue, I will update the version in the tools package. Thank you! Until then I will leave this issue open.
