### ISSUE TITLE
How about add extra field "runtime": VM or Native?

### ISSUE THREAD

**Issue by MaxGraey** [PlummersSoftwareLLC/Primes#561]
This would allow you to filter and compare languages running only in VM or only in native execution. 

For example:
|  #  | Language | ... | Runtime
|----|----|----|----|
|  1  |  C++ | ... | Native
|  2  |  Rust | ... | Native
|  3  |  Zig | ... | Native
| 4  | C# | ... | VM
| 5 | NodeJS | ... | VM
| 6 | Lua | ... | VM

**Comment by rbergen** [comment]
This looks like a remark concerning PrimeView. Please open any issues concerning it on its own repo.

**Comment by MaxGraey** [comment]
Okey. Done!
