### ISSUE TITLE
PrimeCSharp/solution_4 can only build on amd64

### ISSUE THREAD

**Issue by louie-github** [PlummersSoftwareLLC/Primes#594]
The [Dockerfile](https://github.com/PlummersSoftwareLLC/Primes/blob/drag-race/PrimeCSharp/solution_4/Dockerfile) for PrimeCSharp/solution_4 uses the images `mcr.microsoft.com/dotnet/sdk:3.1-focal` and `mcr.microsoft.com/dotnet/runtime:3.1-focal` which are **amd64 specific**, as shown in the Docker Hub README for the .NET [SDK](https://hub.docker.com/_/microsoft-dotnet-sdk/) and [runtime](https://hub.docker.com/_/microsoft-dotnet-runtime/).

Here's an example of a failing build on a Raspberry Pi:
```
pi in louie-pi in Primes/PrimeCSharp/solution_4 on  drag-race via .NET 🎯 netcoreapp3.1 took 2m50s
❯ docker build -t primecsharp4 .
Sending build context to Docker daemon  17.41kB
Step 1/10 : FROM mcr.microsoft.com/dotnet/sdk:3.1-focal AS build
 ---> 006183160a46
Step 2/10 : WORKDIR /source
 ---> Using cache
 ---> c65d99e590e9
Step 3/10 : COPY *.csproj /source
 ---> Using cache
 ---> 4c7165919a87
Step 4/10 : RUN dotnet restore
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
 ---> Running in 6c75ef6310dc
standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c dotnet restore' returned a non-zero code: 1
```

I suggest adding an `arch-amd64` file for this reason.

**Comment by rbergen** [comment]
@louie-github Good spot!

@ItalyToast I think there are two options to address this:

- Add an arch-amd64 file, as @louie-github suggests, or
- Bump the .NET version in the project file and Dockerfile from Core 3.1 to 5.0. The Microsoft-provided .NET 5.0 docker base images are available for arm64. 

I would prefer the second, unless there is a specific reason to stay on Core 3.1.

**Comment by ItalyToast** [comment]
There is no specific reason for Core 3.1. I just copied the dockerfile from solution_2. I think that one is affected aswell. 

Update: I created a PR that updates it to .NET 5. Im new to docker but it builds and runs on my machine, can you verify that it works on your PI @louie-github?
