### ISSUE TITLE
Most languages fail building

### ISSUE THREAD

**Issue by Richhoef** [PlummersSoftwareLLC/Primes#699]
All of a sudden, most languages fail builing: `error: [PrimeCPP][olution_1] Failed building solution!`:
![image](https://user-images.githubusercontent.com/51912545/132091502-d48f0c1a-b658-4cda-910d-6655659285e7.png)

Only a few are able to build:
![image](https://user-images.githubusercontent.com/51912545/132091515-3a64197b-7f25-4078-af03-ba88162aa4a1.png)
Only basic, csharp, powershell and fsharp work

Can anyone help with this? I am running on a Windows 10 pc with WSL2, Ubuntu 20.04, npm 7.21.1, node 14.17.5

**Comment by rbergen** [comment]
I can't reproduce this on my systems.

On your system, in the WSL2 bash shell, could you cd into some of the solution directories for solutions that fail to build, and run `docker build .`? It may give more clues as to why the builds fail.

**Comment by Richhoef** [comment]
This is what I get:
![image](https://user-images.githubusercontent.com/51912545/132094936-ca4e0294-e6ba-466a-b53d-4819e42341d7.png)

**Comment by mike-barber** [comment]
@Richhoef there's no Dockerfile in the PrimeCPP directory, so it won't build anything from there. Try again in `PrimeCPP/solution_1` for instance.

**Comment by Richhoef** [comment]
![image](https://user-images.githubusercontent.com/51912545/132095765-b503566f-b16a-48b3-b6de-db08e911fe93.png)
Now in solution_1

**Comment by mike-barber** [comment]
Ok interesting... I'm not an expert on the things that could go wrong with Docker in Windows. 

It does look like it's failing to log into the Docker server -- I'm not sure if you normally do a docker login or not. But more importantly, it is complaining about not finding a Docker component to handle authentication, so it could potentially be an installation problem. It might be worth trying to re-install Docker, or just reset the engine to its defaults in the UI. It's definitely a strange problem specific to your machine.

The reason some of the solutions build is that you probably already had the base images for them cached on your machine from when Docker was still working correctly. 

Hope that helps

**Comment by Richhoef** [comment]
Thanks a lot for your help! Resetting docker to its default settings seems to have fixed this weird problem!

**Comment by mike-barber** [comment]
@Richhoef awesome! Glad to hear it's sorted!
