### ISSUE TITLE
Handling Legal Questions re: Dyalog APL

### ISSUE THREAD

**Issue by arcfide** [PlummersSoftwareLLC/Primes#741]
> Concerning what's needed on the other topic, I'd suggest that someone who can legally represent Dyalog contacts me via email on rbergen (at) xs4all dot nl, so we can get that conversation going.

_Originally posted by @rbergen in https://github.com/PlummersSoftwareLLC/Primes/issues/722#issuecomment-922211574_

Just wanted to create a separate issue for tracking this. We got the ball rolling on the Dyalog side and @rbergen should have an email regarding this to move forward on.

**Comment by rbergen** [comment]
As far as I'm aware, I have not yet received any e-mail on the topic. Concerning this issue, I'd like to manage expectations: from my side, I do not intend to "shadow" the discussions on the topic on other channels, here.

**Comment by arcfide** [comment]
You should have received an email on the 24th of Sept. from Morten Kromberg to get things started. I wouldn't expect any shadowing on this issue related to the channel, but I wanted to have a public issue at least for the "start and end" points.

**Comment by rbergen** [comment]
Thank you for the very specific pointer, that allowed me to locate the email, indeed. In line with what you're saying, I'll update this issue once I believe that an end point is reached.

**Comment by rbergen** [comment]
I have not received further communication from Dyalog after I replied to their email, 18 days ago. If I also don't in the next 7 days, I will close this issue as "unresolved".

**Comment by arcfide** [comment]
Thanks, I'm escalating and should be able to figure out what the hold up is.

**Comment by rbergen** [comment]
@arcfide I'm letting you know that I intend to close this issue in a week. By that time it's been a month that I haven't had a response to my last email on the matter.

**Comment by Macleykun** [comment]
Small reminder for @arcfide

**Comment by rbergen** [comment]
@Macleykun Current status is not dependent on action from @arcfide.
