### ISSUE TITLE
Number of threads isn't being reported by awk solution 1

### ISSUE THREAD

**Issue by sonicrules1234** [PlummersSoftwareLLC/Primes#779]
PrimeAwk/solution_1 isn't reporting number of threads, thus not being counted by the parser.

**Comment by rbergen** [comment]
Good catch. However, if you believe this is an issue then the best way to go about it is opening a PR to change this.

**Comment by sonicrules1234** [comment]
I was just hoping to let whoever did that solution know.

**Comment by rbergen** [comment]
That works if all contributors keep an eye on the issue list. :) The AWK solution was committed 5 months ago to the day, so its contributor may well have moved on to other things.

It may help to tag them in the issue, but I'd still say submitting a fix is the surest way of getting this addressed.

**Comment by rbergen** [comment]
Closing after merge of #792
