### ISSUE TITLE
Require README for each benchmark 

### ISSUE THREAD

**Issue by pepper-lees** [PlummersSoftwareLLC/Primes#80]
Since we have a lot of benchmarks now, I think it would be beneficial to have each folder have a README with relevant information. Most notably, they should probably contain instructions on how to correctly compile and/or run the benchmarks, including recommended compiler flags if relevant. Also, the creators of said benchmarks may wish to write a little description in the readme explaining what it does and how it differs from the original three.

**Comment by micwoj92** [comment]
This could be added in pull request template as required checkbox.

**Comment by rhbvkleef** [comment]
I would even be inclined to require a `Dockerfile` where possible.

EDIT: We should probably allow multiple `Dockerfile`s, for example in the case runnig withmultiple compilers or interpreters is interesting.
