### ISSUE TITLE
Dart/solution_1 hangs on 5950X runner

### ISSUE THREAD

**Issue by rbergen** [PlummersSoftwareLLC/Primes#809]
We seem to have an issue with Dart/solution_1 since the merge of #808. On Dave's 5950X runner, the parallelized Dart implementations start but never end; the ./PrimeDartParallel or ./PrimeDartParallelOneBit processes keep running and have to be killed manually. This is why no results have been posted from that runner for a number of days.

I'll open a PR to disable the parallel implementations in Dart/solution_1 until this is resolved.

@mmcdon20 What I notice is that the number of child processes on the runner is _less_ than the number of cores/threads of the CPU. Could this somehow be related?

**Comment by rbergen** [comment]
Reopening as #810 is more of a workaround than an actual solution.

**Comment by rbergen** [comment]
I can confirm that the Dart solution does finish during the scheduled benchmark run on the 5950X, now that the parallelized implementations have been disabled.

**Comment by mmcdon20** [comment]
I'm not sure, but there were changes made to isolates in dart 2.15 https://medium.com/dartlang/dart-2-15-7e7a598e508a. Isolates are essentially dart processes. Maybe if I update the code to use the new `Isolate.exit` command it won't hang?

**Comment by rbergen** [comment]
If you don't know then I'm officially clueless :)

What I find odd about this is that the problem does not occur on runners with a lower CPU count, like my own quad-core, hyperthreaded i7-7700HQ.

**Comment by rbergen** [comment]
Closing this after the merge of #811.
