### ISSUE TITLE
OCaml solutions don't build with current version of OCaml

### ISSUE THREAD

**Issue by rbergen** [PlummersSoftwareLLC/Primes#958]
While updating a number of Docker images published on Docker Hub in the context of this project, I found that the OCaml solutions don't build with a current version of OCaml (5.1, to be precise). Two reasons I've been able to identify but also noting that there may be more:

- `corebuild` is no longer available. After reading some documentation it seems to me that `dune` is now "the" build system for OCaml, but I may be wrong.
- `Core.Unix` has been deprecated.

Personally, I am definitely not sufficiently knowledgeable about OCaml to make the modifications that would be required to make the solutions build again.

Without wanting to imply any obligation to look into this by the solutions' author @gkpotter, I'm calling out to him specifically in case he would be willing and able to do so.

**Comment by gkpotter** [comment]
I will look into this!

**Comment by rbergen** [comment]
@gkpotter Thank you, I really appreciate that. Let me know if I can help with anything, like the composition of the base image the solutions now use. The Docker Hub link to that image is <https://hub.docker.com/r/primeimages/ocaml>.  
The Dockerfile that produces that image can be found here: <https://github.com/PlummersSoftwareLLC/OCaml-docker>.
