### ISSUE TITLE
Problem While compiling PrimeCPP/solution 2

### ISSUE THREAD

**Issue by pinguimfu** [PlummersSoftwareLLC/Primes#974]
steps taken:

clone git repo inside a ubuntu 22.04 machine running amd64 hardware (Ryzen 3 3200g)
cd into said directory
apt install dependencies (?) (sudo apt install clang build-essentials libc++-dev  libstdc++-dev)
run run.sh gives me this output:

```
gabriel@blackbox:~/Programas/Primes/PrimeCPP/solution_2$ ./run.sh 
PrimeCPP_PAR.cpp:7:10: fatal error: 'chrono' file not found
#include <chrono>
         ^~~~~~~~
1 error generated.
./run.sh: linha 6: ./primes_par.exe: Arquivo ou diretório inexistente
gabriel@blackbox:~/Programas/Primes/PrimeCPP/solution_2$ 
```

what iam doing wrong?

Thanks for the help

**Comment by rbergen** [comment]
I'm converting this to a Q&A discussion. This is not a project issue but a local problem; CI builds fine, and it works on my machine - and that of at least one other person.
