### ISSUE TITLE
Github Discussions

### ISSUE THREAD

**Issue by minecraftchest1** [PlummersSoftwareLLC/Primes#98]
I think it would be a good idea to enable discussions so that we can collaborate and talk without flooding the issues section with non-issues.

**Comment by rhbvkleef** [comment]
Agreed. I cannot enable it as I´m not admin, so @davepl, could you please either make me admin, or enable this?

**Comment by minecraftchest1** [comment]
Any update on this? Ref:@davepl

**Comment by minecraftchest1** [comment]
Ref: @rhbvkleef

**Comment by rbergen** [comment]
@minecraftchest1: within a few days, we should be in a place where we can sort this out.

**Comment by minecraftchest1** [comment]
Any updates on this?

**Comment by rbergen** [comment]
Yes. @rhbvkleef, @marghidanu and I concluded that it is indeed a good idea to enable Discussions, now that we can. That means setting it up is now on our to-do list.

**Comment by rbergen** [comment]
I've just enabled Discussions on the Primes repository.

**Comment by minecraftchest1** [comment]
Thanks.
